### ISSUE TITLE
Does not support custom statuses

### ISSUE THREAD

**Issue by clarg18** [getsno/freshservice-api#5]
`->getTicketByEmail()`

returns

`Gets\Freshservice\Exceptions\FreshserviceException with message 'Unsupported status'`

if the status is not one of the defaults provided.

**Comment by clarg18** [comment]
Looks like these are hard-coded in the `Ticket` class.

```php
    public const STATUS_OPEN = 2;
    public const STATUS_PENDING = 3;
    public const STATUS_RESOLVED = 4;
    public const STATUS_CLOSED = 5;
```

**Comment by asamofal** [comment]
Hi! Sorry for so long reply.

Regarding Freshservice API documentation only these statuses are available for the tickets. I didn't find the ability to create a custom status, is it possible?

![image](https://user-images.githubusercontent.com/2729547/217500542-80a90034-6ac8-4843-aa13-ad9ec82ace1c.png)

UPD: oh, I found it: `Admin > Field ManagerForm > Fields`

**Comment by asamofal** [comment]
Supporting non-default values _(for statuses or any other ticket fields)_ requires making an extra API call `/api/v2/ticket_form_fields`. 
I can say that the current implementation doesn't ready for that, it requires too many changes. This package was created to fit the requirements of my project, so there are only the entities/endpoints that my project is needed - this is a very little part of what is available on freshservice API.
Unfortunately, I have no time to create and maintain a package with full API support. But you are free to fork this repo...
